"""image_hashes table

Revision ID: 03009a6b42b6
Revises: da8628257c5d
Create Date: 2026-05-16 16:06:01.681563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03009a6b42b6'
down_revision: Union[str, None] = 'da8628257c5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_hashes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('listing_id', sa.String(length=64), nullable=False),
    sa.Column('img_hash', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('image_hashes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_image_hashes_listing_id'), ['listing_id'], unique=False)
        batch_op.create_index('ix_imagehash_hash', ['img_hash'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_hashes', schema=None) as batch_op:
        batch_op.drop_index('ix_imagehash_hash')
        batch_op.drop_index(batch_op.f('ix_image_hashes_listing_id'))

    op.drop_table('image_hashes')
    # ### end Alembic commands ###
