"""user delivery filters

Revision ID: 0777741abcdd
Revises: ce869b712281
Create Date: 2026-05-17 15:06:46.281800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0777741abcdd'
down_revision: Union[str, None] = 'ce869b712281'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('min_score', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('exclude_conditions', sa.String(length=128), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('exclude_shop', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('exclude_shop')
        batch_op.drop_column('exclude_conditions')
        batch_op.drop_column('min_score')

    # ### end Alembic commands ###
