"""listing cache columns

Revision ID: 116075099ca5
Revises: 0777741abcdd
Create Date: 2026-05-17 16:14:00.611485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '116075099ca5'
down_revision: Union[str, None] = '0777741abcdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('report_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('valuation_json', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_column('valuation_json')
        batch_op.drop_column('report_json')
        batch_op.drop_column('processed_at')

    # ### end Alembic commands ###
