"""deal feedback

Revision ID: 277858f66849
Revises: 116075099ca5
Create Date: 2026-05-17 16:24:33.057822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '277858f66849'
down_revision: Union[str, None] = '116075099ca5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deal_feedback',
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('listing_id', sa.String(length=64), nullable=False),
    sa.Column('reaction', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('tg_id', 'listing_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deal_feedback')
    # ### end Alembic commands ###
