"""add is_approved to user

Revision ID: ca481baf9b42
Revises: 58d12c0f68aa
Create Date: 2026-05-31 00:11:04.770153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca481baf9b42'
down_revision: Union[str, None] = '58d12c0f68aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending_alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pendingalert_next_attempt'))

    with op.batch_alter_table('price_observations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_price_observations_source'), ['source'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_approved', sa.Integer(), server_default='0', nullable=False))
        batch_op.alter_column('discovery_enabled',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('discovery_min_profit_rub',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('(7000)'))
        batch_op.alter_column('discovery_min_profit_ratio',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               nullable=False,
               existing_server_default=sa.text('(0.2)'))
        batch_op.alter_column('discovery_city_slug',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               nullable=False,
               existing_server_default=sa.text("'rossiya'"))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('discovery_city_slug',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'rossiya'"))
        batch_op.alter_column('discovery_min_profit_ratio',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               nullable=True,
               existing_server_default=sa.text('(0.2)'))
        batch_op.alter_column('discovery_min_profit_rub',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('(7000)'))
        batch_op.alter_column('discovery_enabled',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.drop_column('is_approved')

    with op.batch_alter_table('price_observations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_price_observations_source'))

    with op.batch_alter_table('pending_alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pendingalert_next_attempt'), ['next_attempt_at'], unique=False)

    # ### end Alembic commands ###
