"""subscription onboarded_at

Revision ID: ce869b712281
Revises: 03009a6b42b6
Create Date: 2026-05-17 14:44:53.082483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce869b712281'
down_revision: Union[str, None] = '03009a6b42b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('onboarded_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_column('onboarded_at')

    # ### end Alembic commands ###
