"""initial schema

Revision ID: da8628257c5d
Revises: 
Create Date: 2026-05-16 15:51:45.576675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da8628257c5d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_state',
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('item_json', sa.Text(), nullable=False),
    sa.Column('score_json', sa.Text(), nullable=False),
    sa.Column('sub_query', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('tg_id', 'message_id')
    )
    with op.batch_alter_table('card_state', schema=None) as batch_op:
        batch_op.create_index('ix_cardstate_created', ['created_at'], unique=False)

    op.create_table('device_catalog',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('brand', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('storage_gb', sa.Integer(), nullable=True),
    sa.Column('ram_gb', sa.Integer(), nullable=True),
    sa.Column('aliases', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand', 'model', 'storage_gb', name='uq_device_identity')
    )
    op.create_table('repair_costs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('brand', sa.String(length=32), nullable=False),
    sa.Column('model_pattern', sa.String(length=64), nullable=False),
    sa.Column('defect_type', sa.String(length=32), nullable=False),
    sa.Column('cost_rub', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand', 'model_pattern', 'defect_type', name='uq_repair_identity')
    )
    op.create_table('sent_alerts',
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('listing_id', sa.String(length=64), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('profit', sa.Integer(), nullable=True),
    sa.Column('verdict', sa.String(length=32), nullable=True),
    sa.Column('condition', sa.String(length=32), nullable=True),
    sa.Column('sub_query', sa.String(length=256), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('tg_id', 'listing_id')
    )
    with op.batch_alter_table('sent_alerts', schema=None) as batch_op:
        batch_op.create_index('ix_sentalert_sent_at', ['sent_at'], unique=False)

    op.create_table('users',
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('paused', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('tg_id')
    )
    op.create_table('listings',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('last_price', sa.Integer(), nullable=True),
    sa.Column('condition', sa.String(length=32), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['device_catalog.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('market_baselines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('condition', sa.String(length=32), nullable=False),
    sa.Column('median_price', sa.Integer(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['device_catalog.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'condition', name='uq_baseline_device_cond')
    )
    with op.batch_alter_table('market_baselines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_market_baselines_device_id'), ['device_id'], unique=False)

    op.create_table('price_observations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('listing_id', sa.String(length=64), nullable=True),
    sa.Column('raw_title', sa.Text(), nullable=True),
    sa.Column('storage_gb', sa.Integer(), nullable=True),
    sa.Column('condition', sa.String(length=32), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['device_catalog.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('price_observations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_price_observations_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_price_observations_observed_at'), ['observed_at'], unique=False)
        batch_op.create_index('ix_priceobs_device_cond', ['device_id', 'condition'], unique=False)

    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('query', sa.String(length=256), nullable=False),
    sa.Column('city_slug', sa.String(length=64), nullable=False),
    sa.Column('min_price', sa.Integer(), nullable=True),
    sa.Column('max_price', sa.Integer(), nullable=True),
    sa.Column('min_battery', sa.Integer(), nullable=True),
    sa.Column('search_pages', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tg_id'], ['users.tg_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscriptions_tg_id'), ['tg_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriptions_tg_id'))

    op.drop_table('subscriptions')
    with op.batch_alter_table('price_observations', schema=None) as batch_op:
        batch_op.drop_index('ix_priceobs_device_cond')
        batch_op.drop_index(batch_op.f('ix_price_observations_observed_at'))
        batch_op.drop_index(batch_op.f('ix_price_observations_device_id'))

    op.drop_table('price_observations')
    with op.batch_alter_table('market_baselines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_market_baselines_device_id'))

    op.drop_table('market_baselines')
    op.drop_table('listings')
    op.drop_table('users')
    with op.batch_alter_table('sent_alerts', schema=None) as batch_op:
        batch_op.drop_index('ix_sentalert_sent_at')

    op.drop_table('sent_alerts')
    op.drop_table('repair_costs')
    op.drop_table('device_catalog')
    with op.batch_alter_table('card_state', schema=None) as batch_op:
        batch_op.drop_index('ix_cardstate_created')

    op.drop_table('card_state')
    # ### end Alembic commands ###
